# https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md
# https://help.apple.com/xcode/mac/9.0/index.html?localePath=en.lproj#/dev7fe737ce0

name: Example
attributes:
  ORGANIZATIONNAME: darkThanBlack
targets:
  # 主工程
  DTBKit_Example:
    type: application
    platform: [iOS]
    platformSuffix: ""
    scheme:
#      buildImplicitDependencies: true
      # testTargets:
      #   - DTBKit_Tests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: org.darkThanBlack.demo.DTBKit
        IPHONEOS_DEPLOYMENT_TARGET: 11.0
        SWIFT_VERSION: 5.0
        # 1: iPhone
        TARGETED_DEVICE_FAMILY: 1
        # 注释以便 Xcode 15.3 Uni-Test 成功运行
        # EXCLUDED_ARCHS[sdk=iphonesimulator*]: arm64
        UILaunchStoryboardName: LaunchScreen
        FRAMEWORK_SEARCH_PATHS:
          - $(inherited)
          - $(PODS_CONFIGURATION_BUILD_DIR)/DTBKit
        LIBRARY_SEARCH_PATHS:
          - $(inherited)
        # 注释以消除 pod 警告
        # OTHER_SWIFT_FLAGS:
        #   - "$(inherited) -D COCOAPODS -D Kitable"
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: $(inherited)
        ENABLE_BITCODE: true
        WARNING_CFLAGS:
        - -Wno-documentation
        - -Wno-unguarded-availability
        - -Wno-strict-prototypes
        - -Wno-implicit-retain-self
      # Ensure DEBUG macro exist
      debug:
        GCC_PREPROCESSOR_DEFINITIONS:
          - $(inherited)
          - DEBUG=1
          - COCOAPODS=1
      release:
        GCC_PREPROCESSOR_DEFINITIONS:
          - $(inherited)
          - COCOAPODS=1
    # If you wanna add some caps...
    # entitlements:
    #   path: example.entitlements
    #   properties:
    #     com.apple.developer.applesignin: ['Default']
    # dependencies:
    #   - framework: StoreKit.framework
    #     embed: false
    sources:
      - "Example"
      - "Resources"
    info:
      path: Resources/info.plist
      properties:
        CFBundleAllowMixedLocalizations: true
        CFBundleDevelopmentRegion: zh_CN
        CFBundleDisplayName: DTBKit
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: 6.0
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: APPL
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        ITSAppUsesNonExemptEncryption: false
        LSRequiresIPhoneOS: true
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
        NSCameraUsageDescription: "如果不允许，您将无法拍摄小视频和照片"
        NSMicrophoneUsageDescription: "如果不允许，您将无法使用语音功能"
        NSPhotoLibraryAddUsageDescription: "如果不允许，您选中的图片将无法加入到系统相册"
        NSPhotoLibraryUsageDescription: "如果不允许，您将无法访问系统相册里的图片"
        UILaunchStoryboardName: LaunchScreen.storyboard
        UIStatusBarStyle: UIStatusBarStyleDarkContent
        # 强行指定方向:
        # UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        # 强行指定颜色模式:
        # UIUserInterfaceStyle: Light
        # FIX: ITMS-90899
        LSMinimumSystemVersion: 13.0
        # Info - url types 
        # CFBundleURLTypes:
        #   - CFBundleTypeRole: Editor
        #     CFBundleURLName: weixin
        #     CFBundleURLSchemes: [com.googleusercontent.apps.35708]

# 专门用于代码覆盖率统计, 避免影响主工程文件引用
name: CodeCoverage
attributes:
  ORGANIZATIONNAME: darkThanBlack
targets:
  # 单独编译每个子模块, 并以 target 的形式依赖
  DTBKit_Core:
    type: framework
    platform: [iOS]
    platformSuffix: ""
    deploymentTarget:
      iOS: 11.0
    # scheme:
    #   testTargets:
    #     - DTBKit_Basic_Tests
    #   gatherCoverageData: true
    sources:
      - path: "../Sources/Core"
    settings:
      base:
        GENERATE_INFOPLIST_FILE: true
        
  DTBKit_Chain:
    type: framework
    platform: [iOS]
    platformSuffix: ""
    deploymentTarget:
      iOS: 11.0
    # scheme:
    #   testTargets:
    #     - DTBKit_Basic_Tests
    #   gatherCoverageData: true
    sources:
      - path: "../Sources/Chain"
    dependencies:
      - target: DTBKit_Core
    settings:
      base:
        GENERATE_INFOPLIST_FILE: true
  DTBKit_Basic:
    type: framework
    platform: [iOS]
    platformSuffix: ""
    deploymentTarget:
      iOS: 11.0
    scheme:
      testTargets:
        - DTBKit_Basic_Tests
      gatherCoverageData: true
    sources:
      - path: "../Sources/Basic"
    dependencies:
      - target: DTBKit_Core
      - target: DTBKit_Chain
    settings:
      base:
        GENERATE_INFOPLIST_FILE: true

  # 用于单独统计子模块的代码覆盖率, 普通测试走 cocoapods 的生成即可
  DTBKit_Basic_Tests:
    type: bundle.unit-test
    platform: [iOS]
    platformSuffix: ""
    sources:
      - path: "../Tests/BasicTests/"
        group: "Unit Tests"
    settings:
      # 以前没有 ``BUNDLE_EXECUTABLE_FOLDER_PATH`` 定义, 参见 https://developer.apple.com/forums/thread/723699
      # TEST_HOST: $(BUILT_PRODUCTS_DIR)/DTBKit_Example.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/DTBKit_Example
      PRODUCT_BUNDLE_IDENTIFIER: org.darkThanBlack.demo.DTBKit
      BUNDLE_LOADER: $(TEST_HOST)
      GENERATE_INFOPLIST_FILE: true
      IPHONEOS_DEPLOYMENT_TARGET: 11.0
      SWIFT_VERSION: 5.0
      # 注释以便 Xcode 15.3 Uni-Test 成功运行
      # EXCLUDED_ARCHS[sdk=iphonesimulator*]: arm64
      CLANG_CXX_LANGUAGE_STANDARD: "gnu++20"
    # 这里不用写
    # dependencies:
    # - target: DTBKit_Basic
    # - target: DTBKit_Example
