# https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md
# https://help.apple.com/xcode/mac/9.0/index.html?localePath=en.lproj#/dev7fe737ce0

name: DTBKit
attributes:
  ORGANIZATIONNAME: darkThanBlack
targets:
  DTBKit_Example:
    type: application
    platform: [iOS]
    platformSuffix: ""
    scheme:
      buildImplicitDependencies: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: org.darkThanBlack.demo.DTBKit
        IPHONEOS_DEPLOYMENT_TARGET: 10.0
        SWIFT_VERSION: 5.0
        TARGETED_DEVICE_FAMILY: 1  # iPhone
        EXCLUDED_ARCHS[sdk=iphonesimulator*]: arm64
        UILaunchStoryboardName: LaunchScreen
        FRAMEWORK_SEARCH_PATHS:
          - $(inherited)
          - $(PODS_CONFIGURATION_BUILD_DIR)/DTBKit
        LIBRARY_SEARCH_PATHS:
          - $(inherited)
        OTHER_SWIFT_FLAGS:
          - "$(inherited) -D COCOAPODS -D DTBKitable"
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: $(inherited)
        ENABLE_BITCODE: false
        WARNING_CFLAGS:
        - -Wno-documentation
        - -Wno-unguarded-availability
        - -Wno-strict-prototypes
        - -Wno-implicit-retain-self
    sources:
      ## Metatata
      - path: "../DTBKit.podspec"
        group: "Metadata"
      - path: "../README.md"
        group: "Metadata"
      - path: "../LICENSE"
        group: "Metadata"
      - path: "Podfile"
        group: "Metadata"
      - path: "project.yml"
        group: "Metadata"
      
      ## Examples
      - path: "DTBKit"
        group: "Examples"
      
      ## Sources
      - path: "../DTBKit/DTBKit.swift"
        group: "Source Codes"
      - path: "../DTBKit/Basic"
        group: "Source Codes"
      - path: "../DTBKit/UIKit"
        group: "Source Codes"
      
      ## Resources
      - path: "../DTBKit/Assets"
        group: "Resources"
      
      
  DTBKit_Basic:
    type: framework
    platform: [iOS]
    platformSuffix: ""
    deploymentTarget:
      iOS: 10.0
    scheme:
      testTargets:
        - DTBKit_Tests
      gatherCoverageData: true
    sources:
      - path: "../DTBKit/DTBKit.swift"
      - path: "../DTBKit/Basic"
    settings:
      base:
        GENERATE_INFOPLIST_FILE: true

  DTBKit_Tests:
    type: bundle.unit-test
    platform: [iOS]
    platformSuffix: ""
    
    sources:
      - path: "../DTBKit/BasicTests/"
        group: "Unit Tests"
    settings:
      # 以前没有 ``BUNDLE_EXECUTABLE_FOLDER_PATH`` 定义
      # https://developer.apple.com/forums/thread/723699
      # TEST_HOST: $(BUILT_PRODUCTS_DIR)/DTBKit_Example.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/DTBKit_Example
      PRODUCT_BUNDLE_IDENTIFIER: org.darkThanBlack.demo.DTBKit
      BUNDLE_LOADER: $(TEST_HOST)
      GENERATE_INFOPLIST_FILE: true
      IPHONEOS_DEPLOYMENT_TARGET: 10.0
      SWIFT_VERSION: 5.0
      EXCLUDED_ARCHS[sdk=iphonesimulator*]: arm64
      CLANG_CXX_LANGUAGE_STANDARD: "gnu++20"
    dependencies:
      - target: DTBKit_Basic
