# https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md
# https://help.apple.com/xcode/mac/9.0/index.html?localePath=en.lproj#/dev7fe737ce0

name: DTBKit
attributes:
  ORGANIZATIONNAME: darkThanBlack
targets:
  DTBKit:
    type: framework
    platform: [iOS]
    platformSuffix: ""
    scheme:
      management:
        shared: true
    info:
      path: DTBKit/info.plist
      properties:
        CFBundleAllowMixedLocalizations: true
        CFBundleDevelopmentRegion: zh_CN
        CFBundleDisplayName: DTBKit
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleGetInfoString: ""
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundlePackageType: APPL
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleSupportedPlatforms: [iPhoneOS]
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: darkThanBlack.carthage.DTBKit
        IPHONEOS_DEPLOYMENT_TARGET: 11.0
        SWIFT_VERSION: 5.0
        TARGETED_DEVICE_FAMILY: 1
        FRAMEWORK_SEARCH_PATHS:
          - $(inherited)
          - $(PODS_CONFIGURATION_BUILD_DIR)/DTBKit
        LIBRARY_SEARCH_PATHS:
          - $(inherited)
        EXCLUDED_ARCHS[sdk=iphonesimulator*]: arm64
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: $(inherited)
        ENABLE_BITCODE: true
        WARNING_CFLAGS:
        - -Wno-documentation
        - -Wno-unguarded-availability
        - -Wno-strict-prototypes
        - -Wno-implicit-retain-self
    sources:
      - path: "./DTBKit"
        excludes:
          - "/Tests"
