workspace 'Demo.xcworkspace'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'Demo' do
  platform :ios, '11.0'

#  pod 'DTBKit', :path => '../', :testspecs => ['Tests']
  
  pod 'DTBKit', :path => '../'
  pod 'DTBKit/UIKit', :path => '../'
  pod 'DTBKit/Map', :path => '../'
  
  pod 'SnapKit', '5.0.1'
#  pod 'URLNavigator', '2.3.0'
  
  pod 'DoraemonKit/Core', '3.1.3', configurations: %w[Debug] # 必选
  pod 'DoraemonKit/WithGPS', '3.1.3', configurations: %w[Debug] # 必选
  
#  target 'DTBKit_Tests' do
#    inherit! :search_paths
#  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'NO'
      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
      config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
      config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
      config.build_settings['GENERATE_INFOPLIST_FILE'] = "NO"
      config.build_settings['SWIFT_VERSION'] = "5.0"
    end
  end
end
