use_frameworks!

platform :ios, '11.0'

target 'Demo' do
  
#  pod 'DTBKit', :path => '../', :testspecs => ['Tests']
  
#  pod 'DTBKit', :path => '../'
  pod 'DTBKit/UIKit', :path => '../'
  
  pod 'SnapKit', '5.0.1'
#  pod 'URLNavigator', '2.3.0'
  
  pod 'DoraemonKit/Core', '3.1.3', configurations: %w[Debug] # 必选
  pod 'DoraemonKit/WithGPS', '3.1.3', configurations: %w[Debug] # 必选
  
#  target 'DTBKit_Tests' do
#    inherit! :search_paths
#  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
    end
  end
end
